# cinemafront-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinemafront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinemafront
  template:
    metadata:
      labels:
        app: cinemafront
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox
          command: ['sh', '-c', 'until nc -z cinemaapp 7999; do echo waiting for cinemaapp; sleep 2; done']
      containers:
        - name: cinemafront
          image: danielsheh/cinema_cinemafront:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cinemafront
spec:
  type: NodePort
  selector:
    app: cinemafront
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
